// Generated by CoffeeScript 1.10.0
(function() {
  var NamedComponent, React;

  React = require('react');

  NamedComponent = React.createClass({displayName: "NamedComponent",
    render: function() {
      var extraProps, i;
      extraProps = {
        style: {
          color: 'red'
        },
        width: 10
      };
      return React.createElement("ul", Object.assign({}, extraProps, {
        "width": 12.
      }), (function() {
        var j, len, ref, results;
        ref = [2, 3, 5];
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          i = ref[j];
          results.push(React.createElement("li", {
            "key": i
          }, i, " ", React.createElement("input", {
            "type": "checkbox",
            "defaultChecked": true
          })));
        }
        return results;
      })());
    }
  });

}).call(this);
